apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: siddesh-helloworld-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-siddesh
    spec:
      containers:
      - name: siddesh-helloworld
        image: siddeshbg/docker-demo:v2
        ports:
        - name: nodejs-port
          containerPort: 3000
