apiVersion: v1
kind: Pod
metadata:
  name: siddesh.helloworld.com
  labels:
    app: helloworld
spec:
  containers:
  - name: siddesh-helloworld
    image: siddeshbg/docker-demo:v2
    ports:
    - name: nodejs-port
      containerPort: 3000
